name: Python Application CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup virtual environment and install test dependencies
      run: make setup install-dev
    - name: Run unit and feature tests
      run: make test-ci
    - name: Publish test report
      uses: n-ryu/test-reporter@v0.0.2
      if: always()
      with:
        name: Test report
        path: "reports/**/*.xml"
        reporter: java-junit
        list-tests: "failed"
    - name: Add test results to summary
      uses: test-summary/action@v2
      if: always()
      with:
        paths: "reports/**/*.xml"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Add coverage report to summary
      run: |
        echo "**Test Coverage Report**" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat reports/coverage_report.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup virtual environment and install test dependencies
      run: make setup install-dev
    - name: Lint with ruff, reformat-gherkin, and mypy
      run: make lint-ci
    - name: Add mypy reports to summary
      run: |
        echo "**Mypy Line Precision Report**" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat reports/mypy/lineprecision.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

        echo "**Mypy \`Any\` Expression Report**" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat reports/mypy/any-exprs.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

        echo "**Mypy Types of \`Any\` Report**" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat reports/mypy/types-of-anys.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
